name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: ['6.0', '7.0', '8.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up the Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Start MongoDB
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    # Step 4: Install Node.js dependencies
    - run: npm install

    # Step 5: Run your application (optional for testing builds)
    - run: npm start
      env:
        DATABASE_CONNECTION: mongodb://localhost:27017/testdb

    # Step 6: Run tests
    - run: npm test
      env:
        DATABASE_CONNECTION: mongodb://localhost:27017/testdb
        CI: true
